Repository wanted-pre-onboarding-frontend-12team/pre-onboarding-7th-2-2-12, pull requests merged in 2022-11, with the labels that each got.

#2 [#1] 도메인 관점 데이터 타입 정의 & 스토리지 모듈 정의
  src/types/advertise.ts
  src/types/media.ts
  src/types/trend.ts
  src/utils/StorageUtils.ts
Labels: 🍱 Support

#6 [#4] Typography 공통 컴포넌트 UI 구현
  src/components/index.ts
  src/components/shared/Typography/index.tsx
  src/components/shared/Typography/styled.ts
Labels: 💄 UI

#5 [#3] 광고 관리 페이지 UI 구현
  src/components/feature/Card/index.tsx
  src/components/feature/Card/styled.ts
  src/components/feature/CardInfo/index.tsx
  src/components/feature/CardInfo/styled.ts
  src/components/feature/CardList/index.tsx
  src/components/feature/CardList/styled.ts
  src/components/feature/CardTitle/index.tsx
  src/components/feature/CardTitle/styled.ts
  src/components/shared/Button/index.tsx
  src/components/shared/Button/styled.ts
  src/pages/ADManagement/index.tsx
  src/pages/ADManagement/styled.ts
Labels: ✨ Feature, 💄 UI

#7 [#8] 사이드바, 헤더 UI 및 메뉴탭 기능 구현
  src/assets/images/SideBarLogo.png
  src/assets/images/Untitled.zip
  src/assets/images/admanagement.svg
  src/assets/images/alarm.svg
  src/assets/images/blue admanagement.svg
  src/assets/images/blue dashboard.svg
  src/assets/images/bulb.svg
  src/assets/images/dashboard.svg
  src/assets/images/setting.svg
  src/assets/images/userIcon.svg
  src/components/layout/Header/index.tsx
  src/components/layout/Header/styled.ts
  src/components/layout/SideBar/index.tsx
  src/components/layout/SideBar/styled.ts
  src/components/shared/Guide/index.tsx
  src/components/shared/Guide/styled.ts
  src/components/shared/MenuTab/index.tsx
  src/components/shared/MenuTab/styled.ts
  src/components/shared/Title/index.tsx
  src/components/shared/Title/styled.ts
  src/pages/ADManagement/index.tsx
  src/pages/ADManagement/styled.ts
  src/pages/DashBoard/index.tsx
  src/pages/DashBoard/styled.ts
Labels: ✨ Feature, 💄 UI

#12 [#11] 레이아웃 컴포넌트 구현 이후, 1차 리팩터링
  src/components/feature/Card/index.tsx
  src/components/feature/Card/styled.ts
  src/components/feature/CardList/index.tsx
  src/components/feature/CardList/styled.ts
  src/components/feature/CardTitle/styled.ts
  src/components/index.ts
  src/components/layout/index.tsx
  src/components/layout/styled.ts
  src/components/shared/Button/styled.ts
  src/components/shared/Title/index.tsx
  src/pages/ADManagement/index.tsx
  src/pages/ADManagement/styled.ts
  src/pages/DashBoard/index.tsx
Labels: 💄 UI, 🔨 Refactor

#14 [#9, #10] 통합광고현황 페이지 내 광고상태창 UI 구현
  .gitignore
  db.json
  package-lock.json
  package.json
  src/api/trend_data.ts
  src/assets/images/down.png
  src/assets/images/up.png
  src/components/DatePicker/index.tsx
  src/components/DatePicker/styled.ts
  src/components/feature/AdStatusItem/index.tsx
  src/components/feature/AdStatusItem/styled.ts
  src/components/feature/AdStatusList/index.tsx
  src/components/feature/AdStatusList/styled.ts
  src/utils/DateUtils.ts
  yarn.lock
Labels: ✨ Feature, 🌐 API, 💄 UI

#16 [#13, #15 ] 차트 UI 구현 및 드롭박스 및 관련 커스텀 훅 구현
  package.json
  src/components/feature/Chart/Chart.tsx
  src/components/shared/DropDown/index.tsx
  src/components/shared/DropDown/styled.ts
  src/constants/dropDownDataList.ts
  src/hooks/useOutsideClick.ts
  yarn.lock
Labels: ✨ Feature, 💄 UI

#17 [#3]광고관리 페이지 수정하기 기능 구현
  src/components/feature/Card/CardInfo/index.tsx
  src/components/feature/Card/CardInfo/styled.ts
  src/components/feature/Card/CardTitle/index.tsx
  src/components/feature/Card/CardTitle/styled.ts
  src/components/feature/Card/index.tsx
  src/components/feature/Card/styled.ts
  src/components/feature/CardList/index.tsx
  src/components/feature/CardTitle/index.tsx
  src/components/index.ts
  src/constants/api.ts
Labels: ✨ Feature, 🎨 Structure

#18 [#15] 드롭박스 UI 구현 및 코드 구조 개선
  src/assets/images/UpArrow.svg
  src/assets/images/bluecircle.svg
  src/assets/images/greencircle.svg
  src/components/shared/DropDown/index.tsx
  src/components/shared/DropDown/styled.ts
Labels: 🎨 Structure, 💄 UI

#19 [#3] 광고 관리 페이지 버그 수정 및 추가 작업
  src/components/feature/Card/index.tsx
  src/constants/api.ts
Labels: 🐛 Bug, 🚑 Bugfix

#22 [#21] 숫자 금액 데이터 XXX원 단위 데이터로 변경하는 유틸 함수 구현
  src/components/feature/Card/index.tsx
  src/utils/NumberUtils.ts
Labels: ✨ Feature, 🍱 Support

#23 [#3] 데이터 딜레이 구현/ 광고 관리 상태값 localStorage에 저장
  src/components/feature/Card/index.tsx
  src/components/feature/Card/styled.ts
  src/components/feature/CardList/index.tsx
  src/pages/ADManagement/index.tsx
  src/pages/ADManagement/styled.ts
Labels: ✨ Feature

#26 통합 광고현황 페이지 내 광고상태창 데이터 렌더링 구현
  db.json
  src/components/DatePicker/index.tsx
  src/components/feature/AdStatusItem/index.tsx
  src/components/feature/AdStatusItem/styled.ts
  src/components/feature/AdStatusList/index.tsx
  src/components/feature/AdStatusList/styled.ts
  src/hooks/useTrendData.ts
  src/pages/DashBoard/index.tsx
  src/utils/KPIUtils.ts
  src/utils/StorageUtils.ts
Labels: ✨ Feature, 🌐 API, 💄 UI, 🚑 Bugfix

#30 Feature/chart
  src/components/feature/Chart/Chart.tsx
  src/components/feature/Chart/styled.ts
  src/components/shared/DropDown/index.tsx
  src/components/shared/DropDown/styled.ts
  src/constants/dropDownDataList.ts
  src/hooks/useDropdown.ts
  src/hooks/useTrendData.ts
  src/pages/DashBoard/index.tsx
Labels: ✨ Feature, 🎨 Structure, 💄 UI

#31 📝 매출액 추가
  src/components/feature/Chart/Chart.tsx
  src/constants/dropDownDataList.ts
Labels: 🎨 Structure

#29 [#28] Select 공통 컴포넌트 UI 구현
  src/assets/images/logo.png
  src/components/index.ts
  src/components/layout/SideBar/index.tsx
  src/components/shared/Select/index.tsx
  src/components/shared/Select/styled.ts
  src/pages/ADManagement/index.tsx
  src/pages/ADManagement/styled.ts
Labels: 💄 UI

#32 Guide컴포넌트 링크 추가 및 사이드바 컴포넌트 드롭다운 추가
  src/components/layout/SideBar/index.tsx
  src/components/layout/SideBar/styled.ts
  src/components/shared/DropDown/styled.ts
  src/components/shared/Guide/index.tsx
  src/components/shared/Guide/styled.ts
Labels: 🎨 Structure

#37 Release 1.0.1
  public/mock/myAds.json
  public/mock/trend.json
  src/api/myAds.ts
  src/api/trend.ts
  src/api/trend_data.ts
  src/components/feature/CardList/index.tsx
  src/components/feature/Chart/index.tsx
  src/constants/api.ts
  src/constants/index.ts
  src/hooks/useTrendData.ts
Labels: 🌐 API

#38 Release 1.0.1
  public/_redirects
Labels: 🚀 Deploy

#39 Release 1.0.3
  src/assets/icons/admanagement.svg
  src/assets/icons/alarm.svg
  src/assets/icons/arrow_down.svg
  src/assets/icons/blue_admanagement.svg
  src/assets/icons/blue_circle.svg
  src/assets/icons/blue_dashboard.svg
  src/assets/icons/bulb.svg
  src/assets/icons/dashboard.svg
  src/assets/icons/green_circle.svg
  src/assets/icons/green_down_triangle.svg
  src/assets/icons/index.ts
  src/assets/icons/logo.svg
  src/assets/icons/red_up_triangle.svg
  src/assets/icons/setting.svg
  src/assets/icons/user.svg
  src/assets/images/Untitled.zip
  src/assets/images/down.png
  src/assets/images/index.ts
  src/assets/images/logo.png
  src/assets/images/up.png
  src/components/feature/AdStatusItem/index.tsx
  src/components/layout/Header/index.tsx
  src/components/layout/SideBar/index.tsx
  src/components/shared/DropDown/index.tsx
  src/components/shared/Guide/index.tsx
  src/components/shared/MenuTab/index.tsx
Labels: 🔨 Refactor, 🍱 Support

#40 Release 1.0.4
  src/components/shared/DropDown/index.tsx
Labels: 💄 UI
